//
// Created by mamin on 1/20/2021.
//
#ifndef STUDIOUS_EUREKA_SRC_EUREKA_TRAITS_ABILITY_H_
#define STUDIOUS_EUREKA_SRC_EUREKA_TRAITS_ABILITY_H_

#endif //STUDIOUS_EUREKA_SRC_EUREKA_TRAITS_ABILITY_H_
